### ISSUE TITLE
Problem with routing

### ISSUE THREAD

**Issue by InnerFireZ** [s0i37/karma#1]
Hello, I need some help to determinate the problem that I face.

When I run the main script karma.py with -d options and -opn network i got clinets, but I can reach them via IP
Here is the output from the script:

[*] checking IP forwarding
[.] [07:54:54] on_client/smb_null.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/bluekeep.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/cisco_smart_install.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/scan.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/rtsp.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[*] scanning common ports
[.] [07:54:54] on_client/interfaces.py 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/www_screenshot.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/rdp_screenshot.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
Starting Nmap 7.94 ( https://nmap.org ) at 2023-08-31 07:54 UTC
[.] [07:54:54] on_client/local_admins.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
**setup_target: failed to determine route to 11.0.0.19**
WARNING: No targets were specified, so 0 hosts scanned.
[.] [07:54:54] on_client/ms17-010.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/bruteforce/ssh.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[*] getting network interfaces via NetBIOS
**[Errno 101] Network is unreachable**
[.] [07:54:54] on_client/bruteforce/smb.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
[.] [07:54:54] on_client/bruteforce/rdp.sh 11.0.0.19 8c:f5:a3:ec:3b:d3 11.0.0.1
**setup_target: failed to determine route to 11.0.0.19**
**WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0**

**Comment by s0i37** [comment]
I will send commit with fixing in near future.
